"""Publish the GVR tree viewer: a public dataset of the trees and a static Space that reads it.

Same safeguards as publish.py, whose credential scan this reuses: every file is scanned before any
upload, and the Space pins the dataset commit it was built against.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

from publish import HERE, REPO, env_values, scan, secret_values

DATA = Path("/checkpoint/fort/anikaitsingh/value_as_tool_tree_viewer/data")


def dataset_card(data, dataset, space):
    overview = json.loads((data / "index" / "overview.json").read_text())
    trees = overview["trees"]
    return f"""---
license: other
viewer: false
pretty_name: Value-as-Tool branched GVR trees on ArXivMath
tags:
- mathematics
- verifiers
- value-functions
- agent-trajectories
---

# Value-as-Tool branched GVR trees on ArXivMath

Branched Generator → Verifier → Reviser (GVR) rollouts behind the
[GVR tree explorer Space](https://huggingface.co/spaces/{space}). There is one tree per
problem for {trees.get('train', 0) + trees.get('eval', 0):,} ArXivMath short-answer problems
({trees.get('train', 0):,} train, {trees.get('eval', 0):,} eval), generated by
`{overview['model']}`.

The model writes a first solution c1. At each of {overview['rounds']} verification points,
{overview['branches']} independent verifier calls judge the current solution, and each verdict
routes one revision: *says correct* → re-check anyway, *minor fix* → revise, *critical flaw* →
regenerate. The first successful revision becomes the next spine solution, so each tree has a
spine c1 → c10 plus three one-step leaves per point. That makes {overview['nodes']:,} candidates
and {overview['verifications']:,} verdicts in total. Every candidate is graded by an external
answer judge ({overview['judge']}).

## Layout

- `index/trees.json.gz`: one row per tree: split, arXiv id, Qwen3.6-35B pass rate and difficulty
  bucket, spine labels c1–c10, counts of correct candidates and distinct answers, and the problem.
- `index/overview.json`: dataset-level tables: label changes by revision mode, verdicts by judge
  label, tree labels by difficulty and spine accuracy by round.
- `index/prompts.json`: one exact prompt per call kind, with the problem, candidate under review and
  verifier feedback replaced by `⟦problem⟧`, `⟦candidate⟧`, `⟦critique⟧` and `⟦category⟧`.
- `trees/<problem>.json.gz`: one tree. `nodes` are candidates with their call index, parent,
  cycle, verification point, branch, spine flag, revision mode, answer group, judge label, tokens
  and text. `verdicts` hold each verifier call's verdict, fault category and critique, keyed by the
  candidate they assessed (`on`). `answers` lists the distinct extracted `\\boxed{{}}` answers.
  `calls` lists every model call, including forced-recovery turns.
- `reasoning/<problem>.json.gz`: private reasoning of every call in that tree, keyed by call index.

Files are gzipped JSON. The flat JSONL export (`nodes.jsonl`, `verifications.jsonl`, `trees.jsonl`)
is produced by `scripts/export_gvr_tree_dataset.py` in the value_as_tool repository.

## Provenance and terms

Problems and gold answers come from
[MathArena/arxivmath-training_outputs](https://huggingface.co/datasets/MathArena/arxivmath-training_outputs)
(CC BY 4.0; MathArena, ETH Zürich SRI Lab), split into train and eval by a hash of the normalized
problem text. The difficulty buckets use MathArena's Qwen3.6-35B attempts. Model outputs are from
Qwen3.5-9B and are subject to its license. Labels come from an automatic judge (98.7% agreement
with MathArena's own grades on 999 Qwen3.6 attempts), so treat individual labels as evidence, not
ground truth. Config fingerprint `{overview['config_fingerprint'][:16]}`.
"""


def space_readme(dataset):
    return f"""---
title: Value-as-Tool GVR Tree Explorer
emoji: 🌳
colorFrom: blue
colorTo: green
sdk: static
app_file: index.html
pinned: false
license: mit
datasets:
- {dataset}
short_description: Branched GVR rollouts of Qwen3.5-9B on ArXivMath
---

# Value-as-Tool GVR Tree Explorer

One branched Generator → Verifier → Reviser tree per ArXivMath problem, from Qwen3.5-9B. Each
tree has 10 verification points with 4 verifier branches each. Every candidate is coloured by an
external answer judge, and every edge shows what the verifier said and which revision it routed:
re-check, revise or regenerate. Click a node to read the candidate, the critique that produced it,
the reasoning traces and the exact prompt template. The **Overview** tab summarises all trees.

This is a static app with no backend. It loads gzipped JSON on demand from
[{dataset}](https://huggingface.co/datasets/{dataset}) at a pinned revision. Model text is rendered
as plain DOM text with a limited Markdown subset, and math is rendered locally with KaTeX (license
in `vendor/katex/LICENSE`). App code is MIT licensed; data terms are in the dataset card.
"""


def config_js(dataset, revision):
    base = f"https://huggingface.co/datasets/{dataset}/resolve/{revision}"
    return f"window.TREE_CONFIG = {{dataBase: '{base}', datasetRepo: '{dataset}'}};\n"


def preflight(data):
    for name in ("trees.json.gz", "overview.json", "prompts.json"):
        assert (data / "index" / name).exists(), f"missing index/{name}; run build_trees.py"
    overview = json.loads((data / "index" / "overview.json").read_text())
    expected = sum(overview["trees"].values())
    trees = list((data / "trees").glob("*.json.gz"))
    reasoning = list((data / "reasoning").glob("*.json.gz"))
    assert len(trees) == len(reasoning) == expected, (
        f"{len(trees)} tree files and {len(reasoning)} reasoning files for {expected} trees"
    )
    size = sum(p.stat().st_size for p in data.rglob("*") if p.is_file() and ".cache" not in p.parts)
    print(f"data: {len(trees)} trees, {size / 1e9:.2f} GB")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data", type=Path, default=DATA)
    parser.add_argument(
        "--namespace", default=None, help="HF user or org; defaults to the token's user"
    )
    parser.add_argument("--dataset-name", default="value-as-tool-gvr-trees")
    parser.add_argument("--space-name", default="value-as-tool-gvr-tree-explorer")
    parser.add_argument("--workers", type=int, default=16)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="run every local check and build the Space, upload nothing",
    )
    args = parser.parse_args()
    data = args.data.resolve()
    space_dir = HERE / "tree_space"

    preflight(data)
    secrets = secret_values()
    print(
        f"scanning for credentials ({len(secrets)} local secret values + token patterns)…",
        flush=True,
    )
    hits = scan(data, secrets) + scan(space_dir, secrets)
    assert not hits, "credential-like content found; refusing to publish:\n" + "\n".join(
        f"  {p}: {f}" for p, f in hits
    )
    print("credential scan: clean")

    token = os.environ.get("HF_TOKEN") or env_values(REPO / ".env").get("HF_TOKEN")
    assert token, f"HF_TOKEN not set and not found in {REPO / '.env'}"
    namespace = args.namespace
    if args.dry_run and namespace is None:
        namespace = "<token-user>"
    from huggingface_hub import HfApi

    api = HfApi(token=token)
    if namespace is None:
        namespace = api.whoami()["name"]
    dataset, space = f"{namespace}/{args.dataset_name}", f"{namespace}/{args.space_name}"
    (data / "README.md").write_text(dataset_card(data, dataset, space))

    staging = Path(tempfile.mkdtemp(prefix="tree-space-"))
    shutil.copytree(space_dir, staging, dirs_exist_ok=True)
    (staging / "README.md").write_text(space_readme(dataset))
    if args.dry_run:
        (staging / "config.js").write_text(config_js(dataset, "<revision>"))
        print(f"dry run: would create public dataset {dataset} and public static Space {space}")
        print(f"staged Space at {staging}")
        return

    api.create_repo(dataset, repo_type="dataset", private=False, exist_ok=True)
    print(
        f"uploading {data} → datasets/{dataset} (resumable; rerun this command if interrupted)…",
        flush=True,
    )
    api.upload_large_folder(
        repo_id=dataset,
        repo_type="dataset",
        folder_path=data,
        num_workers=args.workers,
        ignore_patterns=[".cache/**"],
    )
    revision = api.dataset_info(dataset).sha
    print(f"dataset revision {revision}")
    (staging / "config.js").write_text(config_js(dataset, revision))
    api.create_repo(space, repo_type="space", space_sdk="static", private=False, exist_ok=True)
    api.upload_folder(
        repo_id=space,
        repo_type="space",
        folder_path=staging,
        commit_message=f"GVR tree explorer pinned to {dataset}@{revision[:12]}",
    )
    print(f"\nSpace:   https://huggingface.co/spaces/{space}")
    print(f"Dataset: https://huggingface.co/datasets/{dataset}")


if __name__ == "__main__":
    sys.exit(main())
